# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-18 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habr', '0011_auto_20190318_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='my_article',
            field=models.ManyToManyField(to='habr.Article'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='favorite_articles',
            field=models.ManyToManyField(related_name='favorite_articles', to='habr.Article'),
        ),
    ]
